In [20]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [21]:
data=pd.read_csv('Data/all.csv')
data.head()

Year  PADDY  JOWAR  BAJRA  MAIZE  RAGI  msptur  MOONG  URAD  COTTON  \
0  2001    510  445.0    445    445   445    1200   1200  1200    1625   
1  2002    530  485.0    485    485   485    1320   1320  1320    1675   
2  2003    550  490.0    495    490   490    1325   1335  1335    1695   
3  2004    550  505.0    505    505   505    1360   1370  1370    1725   
4  2005    560  515.0    515    525   515    1390   1410  1410    1760   

        ...        Banana (000 tonnes)  Sugarcane (000 tonnes)  \
0       ...                    13160.0                297208.0   
1       ...                    11975.0                287383.0   
2       ...                    11388.0                233862.0   
3       ...                    11710.0                237088.0   
4       ...                    12105.0                281172.0   

   Tobacco (000 tonnes)  Potatoes (000 tonnes)  Black Pepper (000 tonnes)  \
0                 546.0                23924.0                       62.0   
1                 500.0                23269.0                       72.0   
2                 550.0                23060.0                       73.0   
3                 549.0                23631.0                       73.0   
4                 552.0                23905.0                       93.0   

   Chillies (000 tonnes)  Ginger (000 tonnes)  Coconut (000 tonnes)  \
0                 1069.0                322.0               12963.0   
1                  895.0                280.0               12535.0   
2                 1236.0                302.0               12178.0   
3                 1186.0                359.0               12833.0   
4                 1015.0                391.0               14811.0   

   Turmeric (000 tonnes)  Area in 0000ha  
0                  563.0         3306.12  
1                  522.0         2964.76  
2                  565.0         3439.89  
3                  718.0         2912.10  
4                  852.0         2875.33  

[5 rows x 64 columns]

In [22]:
y=data.msptur
def keep_cols(DataFrame, keep_these):
    """Keep only the columns [keep_these] in a DataFrame, delete
    all other columns. 
    """
    drop_these = list(set(list(DataFrame)) - set(keep_these))
    return DataFrame.drop(drop_these, axis = 1)

x = data.pipe(keep_cols, ['Food Grains (Pulses) - Tur (000 tonnes)', 'Area'])

In [23]:
#x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
#x_train.head()

In [24]:
#x_train.shape

In [25]:
#x_test.head()

In [26]:
#x_test.shape

In [27]:
iris=load_iris()
x,y=iris.data,iris.target
x_train,x_test,y_train,y_test=train_test_split(x,y,
test_size=0.2,
random_state=123)
y_test

array([1, 2, 2, 1, 0, 2, 1, 0, 0, 1, 2, 0, 1, 2, 2, 2, 0, 0, 1, 0, 0, 2,
       0, 2, 0, 0, 0, 2, 2, 0])

In [28]:
from sklearn.linear_model import LinearRegression, LogisticRegression
model=LinearRegression()
model.fit(x_train,y_train)
predictions=model.predict(x_test)
for i in range(len(predictions)):
    predictions[i]=round(predictions[i])
import matplotlib.pyplot as plt
plt.scatter(y_test,predictions)
plt.show()
print(predictions)
print(len(predictions))
print(y_test)
print(len(y_test))
print(type(predictions))
print(type(y_test))

<Figure size 640x480 with 1 Axes>

[ 1.  2.  2.  1. -0.  2.  1. -0.  0.  1.  2. -0.  1.  2.  2.  2. -0. -0.
  1.  0. -0.  1.  0.  2. -0. -0.  0.  2.  2. -0.]
30
[1 2 2 1 0 2 1 0 0 1 2 0 1 2 2 2 0 0 1 0 0 2 0 2 0 0 0 2 2 0]
30
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [29]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report as cr
from sklearn import metrics as ms
results=confusion_matrix(list(y_test),list(predictions))
print(results)
print(ms.accuracy_score(y_test,predictions))
print(cr(y_test,predictions))

[[13  0  0]
 [ 0  6  0]
 [ 0  1 10]]
0.9666666666666667
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.86      1.00      0.92         6
           2       1.00      0.91      0.95        11

   micro avg       0.97      0.97      0.97        30
   macro avg       0.95      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30



In [31]:
import pickle
model = LogisticRegression()
model.fit(x_train, y_train)
filename='finalized.pickle'
pickle.dump(model,open(filename,'wb'))

C:\Users\admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
